/* Built at 2013-08-29 21:06:06 +0200 */
var jaws=function(a){a.TileMap.prototype.findPath=function(a,b,c){"undefined"==typeof c&&(c=!1);var k=parseInt(a[0]/this.cell_size[0]),r=parseInt(a[1]/this.cell_size[1]),n=parseInt(b[0]/this.cell_size[0]);b=parseInt(b[1]/this.cell_size[1]);if(k===n&&r===b)return[{x:a[0],y:a[1]}];for(var e=k,d=r,s=0,l=0,t=2*this.size[0]*this.size[1]+1,m=Array(this.size[0]),g=0;g<this.size[0];g++){m[g]=Array(this.size[1]);for(var f=0;f<this.size[1];f++)m[g][f]=!1}m[e][d]={parent:[],G:0,score:t};a=Array(this.size[0]);
for(g=0;g<this.size[0];g++)for(a[g]=Array(this.size[1]),f=0;f<this.size[1];f++)a[g][f]=!1;for(;e!==n||d!==b;){f=[];0<e&&f.push([e-1,d]);e<this.size[0]-1&&f.push([e+1,d]);0<d&&f.push([e,d-1]);d<this.size[1]-1&&f.push([e,d+1]);for(g=0;g<f.length;g++){var p=f[g][0],q=f[g][1];if(l=0===this.cell(p,q).length&&!c||0<this.cell(p,q).length&&c)l=a[p][q]?!0:!1,l=!l;if(l){var l=s+1,u;u=[p,q];var v=[n,b];u=Math.abs(v[0]-u[0])+Math.abs(v[1]-u[1]);l+=u;if(!m[p][q]||m[p][q]&&m[p][q].score>l)m[p][q]={parent:[e,d],
G:s+1,score:l}}}d=[];p=[];e=t;for(g=s=0;g<this.size[0];g++)for(f=0;f<this.size[1];f++)m[g][f]&&m[g][f].score<e&&(d=[g,f],p=m[g][f].parent,e=m[g][f].score,s=m[g][f].G);if(0===d.length)return[];m[d[0]][d[1]]=!1;e=d[0];d=d[1];a[e][d]={parent:p}}c=[];n=a[e][d];for(c.unshift({x:e*this.cell_size[0],y:d*this.cell_size[1]});e!==k||d!==r;)e=n.parent[0],d=n.parent[1],c.unshift({x:e*this.cell_size[0],y:d*this.cell_size[1]}),n=a[e][d];return c};a.TileMap.prototype.lineOfSight=function(a,b,c){"undefined"==typeof c&&
(c=!1);var k=a[0],r=b[0];a=a[1];b=b[1];var n=Math.abs(r-k),e=Math.abs(b-a),d,s;d=k<r?1:-1;s=a<b?1:-1;for(var l=n-e,t;k!==r||a!==b;){if(c){if(0===this.at(k,a).length)return!1}else if(0<this.at(k,a).length)return!1;t=2*l;t>-e&&(l-=e,k+=d);t<n&&(l+=n,a+=s)}return!0};return a}(jaws||{}),jaws=function(a){a.SpriteList=function(a){if(!(this instanceof arguments.callee))return new arguments.callee(a);this.sprites=[];this.length=0;a&&this.load(a)};a.SpriteList.prototype.add=function(){var h=arguments;1==h.length&&
a.isArray(h[0])&&(h=h[0]);if(1<h.length)for(var b=0;b<h.length;b++)this.sprites.push(h[b]);else this.sprites.push(arguments);this.updateLength();return this};a.SpriteList.prototype.at=function(a){return this.sprites[a]};a.SpriteList.prototype.concat=function(){return this.sprites.concat.apply(this.sprites,arguments)};a.SpriteList.prototype.indexOf=function(a,b){return this.sprites.indexOf(a,b)};a.SpriteList.prototype.join=function(a){return this.sprites.join(a)};a.SpriteList.prototype.lastIndexOf=
function(){return this.sprites.lastIndexOf.apply(this.sprites,arguments)};a.SpriteList.prototype.pop=function(){var a=this.sprites.pop();this.updateLength();return a};a.SpriteList.prototype.push=function(){this.sprites.push.apply(this.sprites,arguments);this.updateLength();return this.length};a.SpriteList.prototype.reverse=function(){this.sprites.reverse()};a.SpriteList.prototype.shift=function(){var a=this.sprites.shift();this.updateLength();return a};a.SpriteList.prototype.slice=function(a,b){return this.sprites.slice(a,
b)};a.SpriteList.prototype.sort=function(){this.sprites.sort.apply(this.sprites,arguments)};a.SpriteList.prototype.splice=function(){var a=this.sprites.splice.apply(this.sprites,arguments);this.updateLength();return a};a.SpriteList.prototype.unshift=function(){this.sprites.unshift.apply(this.sprites,arguments);this.updateLength();return this.length};a.SpriteList.prototype.updateLength=function(){this.length=this.sprites.length};a.SpriteList.prototype.valueOf=function(){return this.toString()};a.SpriteList.prototype.filter=
function(){return this.sprites.filter.apply(this.sprites,arguments)};a.SpriteList.prototype.forEach=function(){this.sprites.forEach.apply(this.sprites,arguments);this.updateLength()};a.SpriteList.prototype.every=function(){return this.sprites.every.apply(this.sprites,arguments)};a.SpriteList.prototype.map=function(){return this.sprites.map.apply(this.sprites,arguments)};a.SpriteList.prototype.reduce=function(){return this.sprites.reduce.apply(this.sprites,arguments)};a.SpriteList.prototype.reduceRight=
function(){return this.sprites.reduceRight.apply(this.sprites,arguments)};a.SpriteList.prototype.some=function(){return this.sprites.some.apply(this.sprites,arguments)};a.SpriteList.prototype.isSpriteList=function(){return!0};a.SpriteList.prototype.load=function(h){function b(b){b.forEach(function(b){var h=b._constructor?eval(b._constructor):b.constructor;a.isFunction(h)&&(a.log.info("Creating "+b._constructor+"("+b.toString()+")",!0),h=new h(b),h._constructor=b._constructor||b.constructor.name,c.push(h))})}
var c=this;a.isArray(h)?h.every(function(a){return a._constructor})?b(h):this.sprites=h:a.isString(h)&&(b(JSON.parse(h)),a.log.info(h));this.updateLength()};a.SpriteList.prototype.remove=function(a){a=this.indexOf(a);-1<a&&this.splice(a,1);this.updateLength()};a.SpriteList.prototype.draw=function(){this.forEach(function(a){a.draw()})};a.SpriteList.prototype.drawIf=function(a){this.forEach(function(b){a(b)&&b.draw()})};a.SpriteList.prototype.update=function(){this.forEach(function(a){a.update()})};
a.SpriteList.prototype.updateIf=function(a){this.forEach(function(b){a(b)&&b.update()})};a.SpriteList.prototype.deleteIf=function(a){this.removeIf(a)};a.SpriteList.prototype.removeIf=function(a){this.sprites=this.filter(function(b){return!a(b)});this.updateLength()};a.SpriteList.prototype.toString=function(){return"[SpriteList "+this.length+" sprites]"};return a}(jaws||{}),jaws=function(a){a.Audio=function b(c){if(!(this instanceof arguments.callee))return new arguments.callee(c);"undefined"!==typeof b?
this.set(c):(a.log.error("jaws.Audio (constructor): 'Audio' object does not exist."),this.audio=null)};a.Audio.prototype.default_options={audio:null,autoplay:!1,loop:!1,volume:0,onend:null,onplay:null,onpause:null,_constructor:null};a.Audio.prototype.set=function(b){a.parseOptions(this,b,this.default_options);if(this.audio)if(a.isString(this.audio))b=a.assets.getPostfix(this.audio),a.assets.file_type[b]&&a.assets.can_play[b]?this.setAudio(this.audio):(a.log.warn("jaws.Audio.set: Unknown or unplayable MIME filetype."),
this.audio=null);else if(a.isArray(this.audio)){for(var c=0;c<this.audio.length;c++)if(a.isString(this.audio[c])&&(b=a.assets.getPostfix(this.audio[c]),a.assets.file_type[b]&&a.assets.can_play[b])){this.setAudio(this.audio[c]);break}this.audio instanceof Audio||(a.log.warn("jaws.Audio.set: No known or playable MIME filetypes were found."),this.audio=null)}else a.log.error("jaws.Audio.set: Passed in 'audio' property is neither a String nor Array"),this.audio=null;return this};a.Audio.prototype.setAudio=
function(b){var c=this;if(a.assets.isLoaded(b)){var k=a.assets.get(b);k instanceof Audio?(this.audio=k,0<=this.volume&&(1>=this.volume&&a.isNumber(this.volume))&&(this.audio.volume=this.volume),this.loop&&(this.audio.loop=this.loop),this.onend&&a.isFunction(this.onend)&&this.audio.addEventListener("end",this.onend),this.onplay&&a.isFunction(this.onplay)&&this.audio.addEventListener("play",this.onplay),this.onpause&&a.isFunction(this.onplay)&&this.audio.addEventListener("pause",this.onpause),this.autoplay&&
(this.audio.autoplay=this.autoplay)):this.audio=null}else a.log.warn("jaws.Audio.setAudio: Audio '"+b+"' not preloaded with jaws.assets.add()."),a.assets.load(b,function(){var k=a.assets.get(b);k instanceof Audio?(c.audio=k,0<=c.volume&&(1>=c.volume&&a.isNumber(c.volume))&&(c.audio.volume=c.volume),c.loop&&(c.audio.loop=c.loop),c.hasOwnProperty("onend")&&a.isFunction(c.onend)&&c.audio.addEventListener("end",c.onend),c.hasOwnProperty("onplay")&&a.isFunction(c.onplay)&&c.audio.addEventListener("play",
c.onplay),c.hasOwnProperty("onpause")&&a.isFunction(c.onplay)&&c.audio.addEventListener("pause",c.onpause),c.autoplay&&(c.audio.autoplay=c.autoplay)):c.audio=null},function(){a.log.error("jaws.Audio.setAudio: Could not load Audio resource URL "+b);c.audio=null});return this};a.Audio.prototype.play=function(){this.audio instanceof Audio?this.audio.play():a.log.error("jaws.Audio.play: Either 'audio' was loaded incorrectly or does not exist")};a.Audio.prototype.stop=function(){this.audio instanceof Audio?
(this.audio.pause(),this.audio.currentTime=0):a.log.error("jaws.Audio.stop: Either 'audio' was loaded incorrectly or does not exist")};a.Audio.prototype.pause=function(){this.audio instanceof Audio?this.audio.pause():a.log.error("jaws.Audio.pause: Either 'audio' was loaded incorrectly or does not exist")};a.Audio.prototype.mute=function(){this.audio instanceof Audio?this.audio.mute=!0:a.log.error("jaws.Audio.mute: Either 'audio' was loaded incorrectly or does not exist")};a.Audio.prototype.unmute=
function(){this.audio instanceof Audio?this.audio.mute=!1:a.log.error("jaws.Audio.unmute: Either 'audio' was loaded incorrectly or does not exist")};a.Audio.prototype.seekTo=function(b){this.audio instanceof Audio?a.isNumber(b)&&(this.audio.currentTime=b<=this.audio.duration?b:this.audio.duration):a.log.warn("jaws.Audio.seekTo: Either 'audio' was loaded incorrectly or does not exist")};a.Audio.prototype.setVolume=function(b){this.audio instanceof Audio?a.isNumber(b)&&(1>=b&&0<=b)&&(this.audio.volume=
b):a.log.warn("jaws.Audio: jaws.setVolume: Either 'audio' was loaded incorrectly or does not exist")};a.Audio.prototype.isLoaded=function(){return this.audio instanceof Audio};a.Audio.prototype.toString=function(){var a="[Audio ";this.audio instanceof Audio?(a+=this.audio.src+", ",a+=this.audio.currentTime+", ",a+=this.audio.duration+", ",a+=this.audio.volume+" ]"):a+="null ]";return a};a.Audio.prototype.attributes=function(){var a=this.options;a._constructor=this._constructor||"jaws.Audio";this.audio instanceof
Audio?(a.audio=this.audio.src,a.loop=this.loop,a.muted=this.audio.muted,a.volume=this.audio.volume):a.audio=null;this.hasOwnProperty("autoplay")&&(a.autoplay=this.autoplay);return a};a.Audio.prototype.toJSON=function(){return JSON.stringify(this.attributes())};return a}(jaws||{});"undefined"!==typeof module&&"exports"in module&&(module.exports=jaws.Audio);
