/* Built at 2013-08-25 11:34:47 +0200 */
var jaws=function(a){a.Audio=function d(c){if(!(this instanceof arguments.callee))return new arguments.callee(c);"undefined"!==typeof d?this.set(c):(a.log.error("jaws.Audio (constructor): 'Audio' object does not exist."),this.audio=null)};a.Audio.prototype.default_options={audio:null,autoplay:!1,loop:!1,volume:0,onend:null,onplay:null,onpause:null,_constructor:null};a.Audio.prototype.set=function(d){a.parseOptions(this,d,this.default_options);if(this.audio)if(a.isString(this.audio))d=a.assets.getPostfix(this.audio),
a.assets.file_type[d]&&a.assets.can_play[d]?this.setAudio(this.audio):(a.log.warn("jaws.Audio.set: Unknown or unplayable MIME filetype."),this.audio=null);else if(a.isArray(this.audio)){for(var c=0;c<this.audio.length;c++)if(a.isString(this.audio[c])&&(d=a.assets.getPostfix(this.audio[c]),a.assets.file_type[d]&&a.assets.can_play[d])){this.setAudio(this.audio[c]);break}this.audio instanceof Audio||(a.log.warn("jaws.Audio.set: No known or playable MIME filetypes were found."),this.audio=null)}else a.log.error("jaws.Audio.set: Passed in 'audio' property is neither a String nor Array"),
this.audio=null;return this};a.Audio.prototype.setAudio=function(d){var c=this;if(a.assets.isLoaded(d)){var e=a.assets.get(d);e instanceof Audio?(this.audio=e,0<=this.volume&&(1>=this.volume&&a.isNumber(this.volume))&&(this.audio.volume=this.volume),this.loop&&(this.audio.loop=this.loop),this.onend&&a.isFunction(this.onend)&&this.audio.addEventListener("end",this.onend),this.onplay&&a.isFunction(this.onplay)&&this.audio.addEventListener("play",this.onplay),this.onpause&&a.isFunction(this.onplay)&&
this.audio.addEventListener("pause",this.onpause),this.autoplay&&(this.audio.autoplay=this.autoplay)):this.audio=null}else a.log.warn("jaws.Audio.setAudio: Audio '"+d+"' not preloaded with jaws.assets.add()."),a.assets.load(d,function(){var e=a.assets.get(d);e instanceof Audio?(c.audio=e,0<=c.volume&&(1>=c.volume&&a.isNumber(c.volume))&&(c.audio.volume=c.volume),c.loop&&(c.audio.loop=c.loop),c.hasOwnProperty("onend")&&a.isFunction(c.onend)&&c.audio.addEventListener("end",c.onend),c.hasOwnProperty("onplay")&&
a.isFunction(c.onplay)&&c.audio.addEventListener("play",c.onplay),c.hasOwnProperty("onpause")&&a.isFunction(c.onplay)&&c.audio.addEventListener("pause",c.onpause),c.autoplay&&(c.audio.autoplay=c.autoplay)):c.audio=null},function(){a.log.error("jaws.Audio.setAudio: Could not load Audio resource URL "+d);c.audio=null});return this};a.Audio.prototype.play=function(){this.audio instanceof Audio?this.audio.play():a.log.error("jaws.Audio.play: Either 'audio' was loaded incorrectly or does not exist")};
a.Audio.prototype.stop=function(){this.audio instanceof Audio?(this.audio.pause(),this.audio.currentTime=0):a.log.error("jaws.Audio.stop: Either 'audio' was loaded incorrectly or does not exist")};a.Audio.prototype.pause=function(){this.audio instanceof Audio?this.audio.pause():a.log.error("jaws.Audio.pause: Either 'audio' was loaded incorrectly or does not exist")};a.Audio.prototype.mute=function(){this.audio instanceof Audio?this.audio.mute=!0:a.log.error("jaws.Audio.mute: Either 'audio' was loaded incorrectly or does not exist")};
a.Audio.prototype.unmute=function(){this.audio instanceof Audio?this.audio.mute=!1:a.log.error("jaws.Audio.unmute: Either 'audio' was loaded incorrectly or does not exist")};a.Audio.prototype.seekTo=function(d){this.audio instanceof Audio?a.isNumber(d)&&(this.audio.currentTime=d<=this.audio.duration?d:this.audio.duration):a.log.warn("jaws.Audio.seekTo: Either 'audio' was loaded incorrectly or does not exist")};a.Audio.prototype.setVolume=function(d){this.audio instanceof Audio?a.isNumber(d)&&(1>=
d&&0<=d)&&(this.audio.volume=d):a.log.warn("jaws.Audio: jaws.setVolume: Either 'audio' was loaded incorrectly or does not exist")};a.Audio.prototype.isLoaded=function(){return this.audio instanceof Audio};a.Audio.prototype.toString=function(){var d="[Audio ";this.audio instanceof Audio?(d+=this.audio.src+", ",d+=this.audio.currentTime+", ",d+=this.audio.duration+", ",d+=this.audio.volume+" ]"):d+="null ]";return d};a.Audio.prototype.attributes=function(){var d=this.options;d._constructor=this._constructor||
"jaws.Audio";this.audio instanceof Audio?(d.audio=this.audio.src,d.loop=this.loop,d.muted=this.audio.muted,d.volume=this.audio.volume):d.audio=null;this.hasOwnProperty("autoplay")&&(d.autoplay=this.autoplay);return d};a.Audio.prototype.toJSON=function(){return JSON.stringify(this.attributes())};return a}(jaws||{});"undefined"!==typeof module&&"exports"in module&&(module.exports=jaws.Audio);
jaws=function(a){a.QuadTree=function(b,d){this.depth=d||0;this.bounds=b||new a.Rect(0,0,a.width,a.height);this.nodes=[];this.objects=[]};a.QuadTree.prototype.clear=function(){this.objects=[];for(var b=0;b<this.nodes.length;b++)"undefined"!==typeof this.nodes[b]&&(this.nodes[b].clear(),delete this.nodes[b])};a.QuadTree.prototype.split=function(){var b=Math.round(this.bounds.width/2),d=Math.round(this.bounds.height/2),c=this.bounds.x,e=this.bounds.y;this.nodes[0]=new a.QuadTree(new a.Rect(c+b,e,b,d),
this.depth+1);this.nodes[1]=new a.QuadTree(new a.Rect(c,e,b,d),this.depth+1);this.nodes[2]=new a.QuadTree(new a.Rect(c,e+d,b,d),this.depth+1);this.nodes[3]=new a.QuadTree(new a.Rect(c+b,e+d,b,d),this.depth+1)};a.QuadTree.prototype.getIndex=function(b){var d=-1,a=this.bounds.x+this.bounds.width/2,e=this.bounds.y+this.bounds.height/2,n=b.y<e&&b.y+b.height<e,e=b.y>e;b.x<a&&b.x+b.width<a?n?d=1:e&&(d=2):b.x>a&&(n?d=0:e&&(d=3));return d};a.QuadTree.prototype.insert=function(b){if(b.hasOwnProperty("x")||
b.hasOwnProperty("y")||b.hasOwnProperty("width")||b.hasOwnProperty("height")){if("undefined"!==typeof this.nodes[0]){var d=this.getIndex(b);if(-1!==d){this.nodes[d].insert(b);return}}this.objects.push(b);"undefined"===typeof this.nodes[0]&&this.split();for(b=0;b<this.objects.length;)d=this.getIndex(this.objects[b]),-1!==d?this.nodes[d].insert(this.objects.splice(b,1)[0]):b++}};a.QuadTree.prototype.retrieve=function(b){if(b.hasOwnProperty("x")||b.hasOwnProperty("y")||b.hasOwnProperty("width")||b.hasOwnProperty("height")){var d=
this.getIndex(b),a=this.objects;if("undefined"!==typeof this.nodes[0])if(-1!==d)a=a.concat(this.nodes[d].retrieve(b));else for(d=0;d<this.nodes.length;d++)a=a.concat(this.nodes[d].retrieve(b));return a}};a.QuadTree.prototype.collide=function(b,d,c){var e=!1,n=new a.QuadTree,l=[];b.forEach||(l.push(b),b=l);d.forEach||(l=[],l.push(d),d=l);d.forEach(function(b){n.insert(b)});b.forEach(function(b){e=a.collide(b,n.retrieve(b),c)});n.clear();return e};return a}(jaws||{});
"undefined"!==typeof module&&"exports"in module&&(module.exports=jaws.QuadTree);
jaws=function(a){a.Parallax=function(b){if(!(this instanceof arguments.callee))return new arguments.callee(b);a.parseOptions(this,b,this.default_options);this.width=b.width||a.width;this.height=b.height||a.height};a.Parallax.prototype.default_options={scale:1,repeat_x:null,repeat_y:null,camera_x:0,camera_y:0,width:null,height:null,layers:[]};a.Parallax.prototype.draw=function(b){for(var d,a=0;a<this.layers.length;a++)for(b=this.layers[a],d=this.repeat_x?-(this.camera_x/b.damping%b.width):-(this.camera_x/
b.damping),b.y=this.repeat_y?-(this.camera_y/b.damping%b.height):-(this.camera_y/b.damping),b.x=d;b.y<this.height;){for(;b.x<this.width&&(0<=b.x+b.width&&0<=b.y+b.height&&b.draw(),b.x+=b.width,this.repeat_x););b.y+=b.height;b.x=d;if(!this.repeat_y)break}};a.Parallax.prototype.addLayer=function(b){b=new a.ParallaxLayer(b);b.scaleAll(this.scale);this.layers.push(b)};a.Parallax.prototype.toString=function(){return"[Parallax "+this.x+", "+this.y+". "+this.layers.length+" layers]"};a.ParallaxLayer=function(b){if(!(this instanceof
arguments.callee))return new arguments.callee(b);this.damping=b.damping||0;a.Sprite.call(this,b)};a.ParallaxLayer.prototype=a.Sprite.prototype;return a}(jaws||{});
jaws=function(a){a.PixelMap=function(b){if(!(this instanceof arguments.callee))return new arguments.callee(b);this.sprite=new a.Sprite(b);this.named_colors=[];this.update()};a.PixelMap.prototype.update=function(b,d){this.data=this.sprite.asCanvasContext().getImageData(0,0,this.sprite.width,this.sprite.height).data};a.PixelMap.prototype.draw=function(){this.sprite.draw()};a.PixelMap.prototype.namedColorAtRect=function(b,d){for(var a=d.x,e=d.y;a<d.right;a++)if(this.namedColorAt(a,e)==b)return this.namedColorAt(a,
e);for(;e<d.bottom;e++)if(this.namedColorAt(a,e)==b)return this.namedColorAt(a,e);for(;a>d.x;a--)if(this.namedColorAt(a,e)==b)return this.namedColorAt(a,e);for(;e>d.y;e--)if(this.namedColorAt(a,e)==b)return this.namedColorAt(a,e);return!1};a.PixelMap.prototype.at=function(b,a){b=parseInt(b);a=parseInt(a)-1;0>a&&(a=0);var c=4*a*this.sprite.width+4*b;return[this.data[c],this.data[c+1],this.data[c+2],this.data[c+3]]};a.PixelMap.prototype.namedColorAt=function(b,a){for(var c=this.at(b,a),e=0;e<this.named_colors.length;e++){var n=
this.named_colors[e].name,l=this.named_colors[e].color;if(l[0]==c[0]&&l[1]==c[1]&&l[2]==c[2]&&l[3]==c[3])return n}};a.PixelMap.prototype.nameColor=function(b,a){this.named_colors.push({name:b,color:a})};return a}(jaws||{});
jaws=function(a){a.SpriteList=function(b){if(!(this instanceof arguments.callee))return new arguments.callee(b);this.sprites=[];this.length=0;b&&this.load(b)};a.SpriteList.prototype.add=function(){var b=arguments;1==b.length&&a.isArray(b[0])&&(b=b[0]);if(1<b.length)for(var d=0;d<b.length;d++)this.sprites.push(b[d]);else this.sprites.push(arguments);this.updateLength();return this};a.SpriteList.prototype.at=function(b){return this.sprites[b]};a.SpriteList.prototype.concat=function(){return this.sprites.concat.apply(this.sprites,
arguments)};a.SpriteList.prototype.indexOf=function(b,a){return this.sprites.indexOf(b,a)};a.SpriteList.prototype.join=function(b){return this.sprites.join(b)};a.SpriteList.prototype.lastIndexOf=function(){return this.sprites.lastIndexOf.apply(this.sprites,arguments)};a.SpriteList.prototype.pop=function(){var b=this.sprites.pop();this.updateLength();return b};a.SpriteList.prototype.push=function(){this.sprites.push.apply(this.sprites,arguments);this.updateLength();return this.length};a.SpriteList.prototype.reverse=
function(){this.sprites.reverse()};a.SpriteList.prototype.shift=function(){var b=this.sprites.shift();this.updateLength();return b};a.SpriteList.prototype.slice=function(b,a){return this.sprites.slice(b,a)};a.SpriteList.prototype.sort=function(){this.sprites.sort.apply(this.sprites,arguments)};a.SpriteList.prototype.splice=function(){var b=this.sprites.splice.apply(this.sprites,arguments);this.updateLength();return b};a.SpriteList.prototype.unshift=function(){this.sprites.unshift.apply(this.sprites,
arguments);this.updateLength();return this.length};a.SpriteList.prototype.updateLength=function(){this.length=this.sprites.length};a.SpriteList.prototype.valueOf=function(){return this.toString()};a.SpriteList.prototype.filter=function(){return this.sprites.filter.apply(this.sprites,arguments)};a.SpriteList.prototype.forEach=function(){this.sprites.forEach.apply(this.sprites,arguments);this.updateLength()};a.SpriteList.prototype.every=function(){return this.sprites.every.apply(this.sprites,arguments)};
a.SpriteList.prototype.map=function(){return this.sprites.map.apply(this.sprites,arguments)};a.SpriteList.prototype.reduce=function(){return this.sprites.reduce.apply(this.sprites,arguments)};a.SpriteList.prototype.reduceRight=function(){return this.sprites.reduceRight.apply(this.sprites,arguments)};a.SpriteList.prototype.some=function(){return this.sprites.some.apply(this.sprites,arguments)};a.SpriteList.prototype.isSpriteList=function(){return!0};a.SpriteList.prototype.load=function(b){function d(b){b.forEach(function(b){var d=
b._constructor?eval(b._constructor):b.constructor;a.isFunction(d)&&(a.log.info("Creating "+b._constructor+"("+b.toString()+")",!0),d=new d(b),d._constructor=b._constructor||b.constructor.name,c.push(d))})}var c=this;a.isArray(b)?b.every(function(b){return b._constructor})?d(b):this.sprites=b:a.isString(b)&&(d(JSON.parse(b)),a.log.info(b));this.updateLength()};a.SpriteList.prototype.remove=function(b){b=this.indexOf(b);-1<b&&this.splice(b,1);this.updateLength()};a.SpriteList.prototype.draw=function(){this.forEach(function(b){b.draw()})};
a.SpriteList.prototype.drawIf=function(b){this.forEach(function(a){b(a)&&a.draw()})};a.SpriteList.prototype.update=function(){this.forEach(function(b){b.update()})};a.SpriteList.prototype.updateIf=function(b){this.forEach(function(a){b(a)&&a.update()})};a.SpriteList.prototype.deleteIf=function(b){this.removeIf(b)};a.SpriteList.prototype.removeIf=function(b){this.sprites=this.filter(function(a){return!b(a)});this.updateLength()};a.SpriteList.prototype.toString=function(){return"[SpriteList "+this.length+
" sprites]"};return a}(jaws||{});
jaws=function(a){a.TileMap=function(b){if(!(this instanceof arguments.callee))return new arguments.callee(b);a.parseOptions(this,b,this.default_options);this.cells=Array(this.size[0]);for(var d=0;d<this.size[0];d++){this.cells[d]=Array(this.size[1]);for(var c=0;c<this.size[1];c++)this.cells[d][c]=[]}};a.TileMap.prototype.default_options={cell_size:[32,32],size:[100,100],sortFunction:null};a.TileMap.prototype.clear=function(){for(var b=0;b<this.size[0];b++)for(var a=0;a<this.size[1];a++)this.cells[b][a]=
[]};a.TileMap.prototype.sortCells=function(b){for(var a=0;a<this.size[0];a++)for(var c=0;c<this.size[1];c++)this.cells[a][c].sort(b)};a.TileMap.prototype.push=function(b){var a=this;if(b.forEach)return b.forEach(function(b){a.push(b)}),b;if(b.rect)return this.pushAsRect(b,b.rect());var c=parseInt(b.x/this.cell_size[0]),e=parseInt(b.y/this.cell_size[1]);return this.pushToCell(c,e,b)};a.TileMap.prototype.pushAsPoint=function(b){if(Array.isArray(b)){for(var a=0;a<b.length;a++)this.pushAsPoint(b[a]);
return b}var a=parseInt(b.x/this.cell_size[0]),c=parseInt(b.y/this.cell_size[1]);return this.pushToCell(a,c,b)};a.TileMap.prototype.pushAsRect=function(b,a){for(var c=parseInt(a.x/this.cell_size[0]),e=parseInt((a.right-1)/this.cell_size[0]);c<=e;c++)for(var n=parseInt(a.y/this.cell_size[1]),l=parseInt((a.bottom-1)/this.cell_size[1]);n<=l;n++)this.pushToCell(c,n,b);return b};a.TileMap.prototype.pushToCell=function(b,a,c){this.cells[b][a].push(c);this.sortFunction&&this.cells[b][a].sort(this.sortFunction);
return this};a.TileMap.prototype.at=function(b,a){var c=parseInt(b/this.cell_size[0]),e=parseInt(a/this.cell_size[1]);return this.cells[c][e]};a.TileMap.prototype.atRect=function(b){var a=[];try{var c=parseInt(b.x/this.cell_size[0]);0>c&&(c=0);var e=parseInt(b.right/this.cell_size[0]);e>=this.size[0]&&(e=this.size[0]-1);var n=parseInt(b.y/this.cell_size[1]);0>n&&(n=0);var l=parseInt(b.bottom/this.cell_size[1]);l>=this.size[1]&&(l=this.size[1]-1);for(b=c;b<=e;b++)for(c=n;c<=l;c++)this.cells[b][c].forEach(function(b,
c){-1==a.indexOf(b)&&a.push(b)})}catch(g){}return a};a.TileMap.prototype.all=function(){for(var b=[],a=0;a<this.size[0];a++)for(var c=0;c<this.size[1];c++)this.cells[a][c].forEach(function(a,d){b.push(a)});return b};a.TileMap.prototype.cell=function(b,a){return this.cells[b][a]};a.TileMap.prototype.findPath=function(b,a,c){"undefined"==typeof c&&(c=!1);var e=parseInt(b[0]/this.cell_size[0]),n=parseInt(b[1]/this.cell_size[1]),l=parseInt(a[0]/this.cell_size[0]);a=parseInt(a[1]/this.cell_size[1]);if(e===
l&&n===a)return[{x:b[0],y:b[1]}];for(var g=e,f=n,s=0,m=0,t=2*this.size[0]*this.size[1]+1,p=Array(this.size[0]),k=0;k<this.size[0];k++){p[k]=Array(this.size[1]);for(var h=0;h<this.size[1];h++)p[k][h]=!1}p[g][f]={parent:[],G:0,score:t};b=Array(this.size[0]);for(k=0;k<this.size[0];k++)for(b[k]=Array(this.size[1]),h=0;h<this.size[1];h++)b[k][h]=!1;for(;g!==l||f!==a;){h=[];0<g&&h.push([g-1,f]);g<this.size[0]-1&&h.push([g+1,f]);0<f&&h.push([g,f-1]);f<this.size[1]-1&&h.push([g,f+1]);for(k=0;k<h.length;k++){var q=
h[k][0],r=h[k][1];if(m=0===this.cell(q,r).length&&!c||0<this.cell(q,r).length&&c)m=b[q][r]?!0:!1,m=!m;if(m){var m=s+1,u;u=[q,r];var v=[l,a];u=Math.abs(v[0]-u[0])+Math.abs(v[1]-u[1]);m+=u;if(!p[q][r]||p[q][r]&&p[q][r].score>m)p[q][r]={parent:[g,f],G:s+1,score:m}}}f=[];q=[];g=t;for(k=s=0;k<this.size[0];k++)for(h=0;h<this.size[1];h++)p[k][h]&&p[k][h].score<g&&(f=[k,h],q=p[k][h].parent,g=p[k][h].score,s=p[k][h].G);if(0===f.length)return[];p[f[0]][f[1]]=!1;g=f[0];f=f[1];b[g][f]={parent:q}}c=[];l=b[g][f];
for(c.unshift({x:g*this.cell_size[0],y:f*this.cell_size[1]});g!==e||f!==n;)g=l.parent[0],f=l.parent[1],c.unshift({x:g*this.cell_size[0],y:f*this.cell_size[1]}),l=b[g][f];return c};a.TileMap.prototype.lineOfSight=function(b,a,c){"undefined"==typeof c&&(c=!1);var e=b[0],n=a[0];b=b[1];a=a[1];var l=Math.abs(n-e),g=Math.abs(a-b),f,s;f=e<n?1:-1;s=b<a?1:-1;for(var m=l-g,t;e!==n||b!==a;){if(c){if(0===this.at(e,b).length)return!1}else if(0<this.at(e,b).length)return!1;t=2*m;t>-g&&(m-=g,e+=f);t<l&&(m+=l,b+=
s)}return!0};a.TileMap.prototype.toString=function(){return"[TileMap "+this.size[0]+" cols, "+this.size[1]+" rows]"};return a}(jaws||{});"undefined"!==typeof module&&"exports"in module&&(module.exports=jaws.TileMap);
jaws=function(a){a.TileMap.prototype.findPath=function(b,a,c){"undefined"==typeof c&&(c=!1);var e=parseInt(b[0]/this.cell_size[0]),n=parseInt(b[1]/this.cell_size[1]),l=parseInt(a[0]/this.cell_size[0]);a=parseInt(a[1]/this.cell_size[1]);if(e===l&&n===a)return[{x:b[0],y:b[1]}];for(var g=e,f=n,s=0,m=0,t=2*this.size[0]*this.size[1]+1,p=Array(this.size[0]),k=0;k<this.size[0];k++){p[k]=Array(this.size[1]);for(var h=0;h<this.size[1];h++)p[k][h]=!1}p[g][f]={parent:[],G:0,score:t};b=Array(this.size[0]);for(k=
0;k<this.size[0];k++)for(b[k]=Array(this.size[1]),h=0;h<this.size[1];h++)b[k][h]=!1;for(;g!==l||f!==a;){h=[];0<g&&h.push([g-1,f]);g<this.size[0]-1&&h.push([g+1,f]);0<f&&h.push([g,f-1]);f<this.size[1]-1&&h.push([g,f+1]);for(k=0;k<h.length;k++){var q=h[k][0],r=h[k][1];if(m=0===this.cell(q,r).length&&!c||0<this.cell(q,r).length&&c)m=b[q][r]?!0:!1,m=!m;if(m){var m=s+1,u;u=[q,r];var v=[l,a];u=Math.abs(v[0]-u[0])+Math.abs(v[1]-u[1]);m+=u;if(!p[q][r]||p[q][r]&&p[q][r].score>m)p[q][r]={parent:[g,f],G:s+1,
score:m}}}f=[];q=[];g=t;for(k=s=0;k<this.size[0];k++)for(h=0;h<this.size[1];h++)p[k][h]&&p[k][h].score<g&&(f=[k,h],q=p[k][h].parent,g=p[k][h].score,s=p[k][h].G);if(0===f.length)return[];p[f[0]][f[1]]=!1;g=f[0];f=f[1];b[g][f]={parent:q}}c=[];l=b[g][f];for(c.unshift({x:g*this.cell_size[0],y:f*this.cell_size[1]});g!==e||f!==n;)g=l.parent[0],f=l.parent[1],c.unshift({x:g*this.cell_size[0],y:f*this.cell_size[1]}),l=b[g][f];return c};a.TileMap.prototype.lineOfSight=function(b,a,c){"undefined"==typeof c&&
(c=!1);var e=b[0],n=a[0];b=b[1];a=a[1];var l=Math.abs(n-e),g=Math.abs(a-b),f,s;f=e<n?1:-1;s=b<a?1:-1;for(var m=l-g,t;e!==n||b!==a;){if(c){if(0===this.at(e,b).length)return!1}else if(0<this.at(e,b).length)return!1;t=2*m;t>-g&&(m-=g,e+=f);t<l&&(m+=l,b+=s)}return!0};return a}(jaws||{});
